### ISSUE TITLE
 Restricción de acceso a nivel documentación /api/*

### ISSUE THREAD

**Issue by cmllamosas** [ROAResearch/yii2-roa#3]
Restricción de acceso a nivel documentación /api/*

- **Pasos para reproducir el error:**

1. Clonar el repositorio de yii2-app-roa
2. Instalar workflow
3. Correr composer deploy
4. Configurar el Version Container de la siguiente forma

```
<?php

namespace backend\api;

use roaresearch\yii2\oauth2server\filters\auth\CompositeAuth;
use yii\filters\auth\{HttpBearerAuth, QueryParamAuth};
use yii\helpers\ArrayHelper;

class VersionContainer extends \roaresearch\yii2\roa\modules\ApiContainer
{
    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => CompositeAuth::class,
                'oauth2Module' => $this->getOauth2Module(),
                'authMethods' => [
                    ['class' => HttpBearerAuth::class],
                    [
                        'class' => QueryParamAuth::class,
                        // !Important, GET request parameter to get the token.
                        'tokenParam' => 'accessToken',
                    ],
                ],
                 // no requerir token para generar token
                'except' => [$this->oauth2ModuleId . '/*'],
            ],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public $identityClass = models\User::class;

    /**
     * @inheritdoc
     */
    public $versions = [
        'v1' => [
            'class' => v1\Version::class,
        ],
        'dev' => [
            'class' => v1\Version::class,
        ],
        'w1' => [
            'class' => 'roaresearch\yii2\workflow\roa\modules\Version',
        ],
    ];
}
```
- **Resultado Actual:**

Podemos ver que aparece un error de servidor error 500 con authorization vencido y sin authorization

     imagen con authorization vencido (con la configuración del pastebin del punto 4)

<img width="766" alt="Screen Shot 2020-03-13 at 14 49 35" src="https://user-images.githubusercontent.com/56414144/76658566-08e5ae00-653a-11ea-90cb-9c03d5dffd09.png">

     imagen sin authorization (con la configuración del pastebin del punto 4)

<img width="759" alt="Screen Shot 2020-03-13 at 14 49 23" src="https://user-images.githubusercontent.com/56414144/76658561-05eabd80-653a-11ea-98f3-cb48d7770abe.png">

     imagen con authorization (con la configuración del pastebin del punto 4)

<img width="763" alt="Screen Shot 2020-03-13 at 14 49 06" src="https://user-images.githubusercontent.com/56414144/76658536-f4091a80-6539-11ea-81be-1a813902c07a.png">

- Resultado esperado:
El resultado esperado es Unauthorized
<img width="724" alt="Screen Shot 2020-03-13 at 14 46 08" src="https://user-images.githubusercontent.com/56414144/76658290-675e5c80-6539-11ea-9b3e-916c9ff2cb3f.png">

**Comment by agSoftDUCK** [comment]
Se puede solucionar agregando las siguientes lineas a `behaviors() ` de ApiContainer 

                    'index/*', // controller that return this module info
                    '*/options', // all OPTIONS actions for CORS preflight

De esa manera no solicitará credenciales para /api/ o /api/v1 ni para ningun request OPTIONS

**Comment by cmllamosas** [comment]
@aguevaraIL Lo que esperaría es que regrese un 401 y no lo que describo en el issue, para el caso de añadir un except para 'index/*' o '*/options', no soluciona lo que reporto.

**Comment by agSoftDUCK** [comment]
No veo por que debería devolver 401. Al ser el punto de acceso no hay necesidad de solicitar credenciales para que pueda acceder a la documentación y especificación técnica de las versiones soportadas.

¿Qué pasa si un desarrollador quiere obtener la documentación para crear un APP? Es posible que el desarrollador nunca tenga credenciales de acceso a ningún API. Y aún así necesitará saber si cada versión es estable.

**Comment by cmllamosas** [comment]
Ok, @aguevaraIL  pero que sucede si el api no quieres que nadie tenga acceso y solo si tienes credenciales y los permisos para visualizarla.

Ej: API Bancaria, solo le das permisos a ver la documentación con un acceso.

**Comment by agSoftDUCK** [comment]
@cmllamosas se usa rbac para limitar el acceso a los recursos de cada api version
